
title: Home
baseurl: "" 
url: "https://addairabi.github.io/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Hapus konfigurasi sass jika tidak digunakan
theme: null

# Tambahkan konfigurasi default untuk feed
jekyll-feed:
  path: "feed.xml"