name: Jekyll Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Versi yang didukung github-pages v232
          bundler-cache: true

      - name: Fix Platform Issues
        run: |
          bundle lock --add-platform x86_64-linux
          bundle lock --add-platform ruby
          bundle lock --remove-platform x64-mingw-ucrt

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential patch zlib1g-dev liblzma-dev
          bundle config set force_ruby_platform true
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --trace

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site